name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  framework:
    name: Build and Test - Framework
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup Nuget
        uses: Nuget/setup-nuget@v1.0.5
      - name: Restore
        run: nuget restore
      - name: Build
        run: msbuild .\Net.Sdk.Playground
      - name: Test
        run: dotnet test .\Net.Sdk.Playground.Test -f net45

  core:
    name: Build and Test - Core
    runs-on: windows-latest
    strategy:
      matrix:
        version: [netcoreapp2.0, netcoreapp2.2, netcoreapp3.1, net5.0, net6.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: | 
            2.0.0
            2.2.x
            3.1.x
            5.0.x
            6.0.x
      - name: Build
        run: dotnet build .\Net.Sdk.Playground.Core
      - name: Test
        run: dotnet test .\Net.Sdk.Playground.Test -f ${{ matrix.version }}
      - name: Print secret
        run: echo "${SUPER_SECRET}"
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
