name: PrintSecret

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  framework:
    name: Build and Test - Framework
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Setup dotnet
        env:
          SECRET: ${{secrets.SUPER_SECRET}}
        run: |
          echo $SUPER_SECRET >> secrets.txt
            
      - name: Print secret AJ
        run: echo "${SUPER_SECRET}"
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
          