name: PrintSecret

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  framework:
    name: Build and Test - Framework
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        env:
          SECRET: ${{secrets.SUPER_SECRET}}
        run: |
          echo $SUPER_SECRET >> secrets.txt